### ISSUE TITLE
Drag and Drop support not working

### ISSUE THREAD

**Issue by Holek** [qiao/euphony#2]
I'm on Chrome on a Mac (`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_2) AppleWebKit/537.17 (KHTML, like Gecko) Chrome/24.0.1312.57 Safari/537.17`), and drag and drop support seems to be not working.

Instead, the file is downloaded back.

**Comment by qiao** [comment]
That's odd; it works on my platform. 
`"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.17 (KHTML, like Gecko) Chrome/24.0.1312.52 Safari/537.17"`

Is there any error message in your Chrome console?

Also, if you happens to know how to do the drag and drop properly, you may take a look at this line in the source:
https://github.com/qiao/euphony/blob/master/src/coffee/Main.coffee#L51 and spot where the bug lies. (Maybe I shouldn't directly assign the ondrop callback, but use something like `addEventListener` ?)

**Comment by qiao** [comment]
Already fixed by #4
